packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

catalog:
  '@hono/node-server': ^1.14.4
  '@stylistic/eslint-plugin': ^4.4.1
  '@types/node': ^24.0.1
  '@typescript-eslint/utils': ^8.34.0
  '@vitest/coverage-v8': ^3.2.3
  ansis: ^4.1.0
  eslint: ^9.28.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-import-x: ^4.15.2
  eslint-plugin-jsdoc: ^50.8.0
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-perfectionist: ^4.14.0
  globals: ^16.2.0
  hono: ^4.7.11
  jiti: ^2.4.2
  json-schema-to-typescript-lite: ^14.1.0
  prettier: ^3.5.3
  svelte: ^5.34.1
  tinyglobby: ^0.2.14
  tsup: ^8.5.0
  tsx: ^4.19.4
  turbo: ^2.5.4
  typescript: ^5.8.3
  'typescript-eslint': ^8.34.0
  vitest: ^3.2.3

catalogs:
  peer:
    '@eslint-react/eslint-plugin': ^1.52.1
    eslint: ^9.28.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-svelte: ^3.9.2
    prettier: ^3.5.3
