packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

catalog:
  '@hono/node-server': ^1.14.1
  '@stylistic/eslint-plugin': ^4.2.0
  '@types/node': ^22.15.17
  '@typescript-eslint/utils': ^8.32.0
  '@vitest/coverage-v8': ^3.1.3
  ansis: ^4.0.0
  eslint: ^9.26.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-import-x: ^4.11.1
  eslint-plugin-jsdoc: ^50.6.12
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-perfectionist: ^4.12.3
  globals: ^16.1.0
  hono: ^4.7.9
  jiti: ^2.4.2
  json-schema-to-typescript-lite: ^14.1.0
  prettier: ^3.5.3
  svelte: ^5.28.2
  tsup: ^8.4.0
  tsx: ^4.19.4
  turbo: ^2.5.3
  typescript: ^5.8.3
  'typescript-eslint': ^8.32.0
  vitest: ^3.1.3

catalogs:
  peer:
    '@eslint-react/eslint-plugin': ^1.49.0
    eslint: ^9.26.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-svelte: ^3.5.1
    prettier: ^3.5.3
