packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

catalogs:
  dev:
    '@gicho/config': ^0.0.1-alpha.6
    '@hono/node-server': ^1.14.4
    '@types/node': ^24.0.1
    '@vitest/coverage-v8': ^3.2.3
    ansis: ^4.1.0
    eslint: ^9.32.0
    hono: ^4.7.11
    jiti: ^2.4.2
    prettier: ^3.6.2
    tinyglobby: ^0.2.14
    tsdown: ^0.12.9
    tsx: ^4.19.4
    turbo: ^2.5.4
    typescript: ^5.8.3
    vitest: ^3.2.3
    wrap-ansi: ^9.0.0
