packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

catalog:
  '@stylistic/eslint-plugin': ^4.2.0
  '@types/node': ^22.15.3
  '@typescript-eslint/utils': ^8.31.1
  ansis: ^3.17.0
  eslint: ^9.25.1
  eslint-config-flat-gitignore: ^2.1.0
  eslint-config-prettier: ^10.1.2
  eslint-plugin-import-x: ^4.11.0
  eslint-plugin-jsdoc: ^50.6.11
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-perfectionist: ^4.12.3
  globals: ^16.0.0
  jiti: ^2.4.2
  json-schema-to-typescript-lite: ^14.1.0
  prettier: ^3.5.3
  svelte: ^5.28.2
  tsup: ^8.4.0
  tsx: ^4.19.3
  turbo: ^2.5.2
  typescript: ^5.8.3
  'typescript-eslint': ^8.31.1

catalogs:
  peer:
    '@eslint-react/eslint-plugin': ^1.48.5
    eslint: ^9.25.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-svelte: ^3.5.1
    prettier: ^3.5.3
