packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

catalogs:
  dev:
    '@gicho/config': ^0.0.1-alpha.10
    '@hono/node-server': ^1.18.1
    '@types/node': ^24.2.0
    '@vitest/coverage-v8': ^3.2.4
    ansis: ^4.1.0
    eslint: ^9.32.0
    hono: ^4.8.12
    jiti: ^2.5.1
    prettier: ^3.6.2
    tinyglobby: ^0.2.14
    tsdown: ^0.13.3
    tsx: ^4.20.3
    typescript: ^5.8.3
    vitest: ^3.2.4
